name: 溜溜球上班

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'Actions'
        required: false
        default: 'false'

  schedule:
    - cron: '55 23 * * *' # +8小时为北京时间
  watch:
    types: started  
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 设置时区
        run: sudo timedatectl set-timezone 'Asia/Shanghai'

      - name: 拉取代码
        uses: actions/checkout@v2

      - name: Node 环境
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: 安装依赖
        run: npm install    

      # - name: 清理
      #   run: node null.js

      # - name: 提交清理
      #   run: |
      #     git add .
      #     git commit -m "clearFile"    
      - name: 运行
        run: npm start
        
        env:
          imie: ${{ secrets.imie }}
          token: ${{ secrets.token }}
          psncode: ${{ secrets.psncode }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
