name: 更新说明

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'Actions'
        required: false
        default: 'false'

  schedule:
    - cron: '0 0 * * 1'
  watch:
    types: started  
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 设置时区
        run: sudo timedatectl set-timezone 'Asia/Shanghai'

      - name: 拉取代码
        uses: actions/checkout@v2

      - name: Node 环境
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Git 环境
        run: |
          git config --local user.email "349690177@qq.com"
          git config --local user.name "numens"
      - name: 安装依赖
        run: npm install    

      - name: 运行
        run: npm update

      - name: 提交
        run: |
          git add .
          git commit -m "$(date '+%Y-%m-%d %H:%M:%S') update"
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GIT_TOKEN }}